version: '3.7'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=mypassw0rd
      - POSTGRES_DB=codimd
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    networks:
      - internal

  app:
    image: hackmdio/hackmd:${VERSION:-1.3.1-alpine}
    environment:
      - HMD_DB_URL=postgres://codimd:mypassw0rd@postgres:5432/codimd
    deploy:
      labels:
        - traefik.port=3000
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-codimd.localhost}
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - internal
      - traefik

volumes:
  postgres:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
