version: '3.7'

services:
  nginx:
    image: ethibox/nginx-proxy:latest
    command:
      - /bin/sh
      - -c
      - |
        envsubst '$$NGINX_ROOT_PATH' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf
        sed -i -e 's/app:9000/'$$STACK_NAME'_app:9000/g' /etc/nginx/nginx.conf
        nginx -g 'daemon off;'
    environment:
      - STACK_NAME={{ index .Service.Labels "com.docker.stack.namespace" }}
      - NGINX_ROOT_PATH=/var/www/html/public
    volumes:
      - ${VOLUME_PATH}data:/var/www/html:cached
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-crater.localhost}
    networks:
      - internal
      - traefik
    
  app:
    image: ethibox/crater:${VERSION:-2.1.0}
    volumes:
      - ${VOLUME_PATH}data:/var/www/html:cached
    networks:
      - internal

  mariadb:
    image: mariadb:10.3.14
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=crater
      - MYSQL_USER=crater
      - MYSQL_PASSWORD=myp@ssw0rd
    networks:
      - internal

volumes:
  data:
  mariadb:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
