version: '3.7'

services:
  web:
    image: etherpad/etherpad:latest
    environment:
      - NODE_ENV=production
      - DB_TYPE=mysql
      - DB_HOST=mariadb
      - DB_NAME=${MYSQL_DATABASE:-etherpad}
      - DB_USER=${MYSQL_USER:-etherpad}
      - DB_PASS=${MYSQL_PASSWORD:-myp@ssw0rd}
    labels:
      - traefik.enable=true
      - traefik.http.routers.etherpad.rule=Host(`${DOMAIN:-etherpad.localhost}`)
      - traefik.http.routers.etherpad.tls=${HTTPS:-false}
      - traefik.http.routers.etherpad.tls.certresolver=mytlschallenge
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.3.12
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=${MYSQL_USER:-etherpad}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-etherpad}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    networks:
      - internal

volumes:
  mariadb:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
