# git clone https://framagit.org/framasoft/framadate/framadate.git data

version: '3.7'

services:
  framadate:
    image: ethibox/framadate:latest
    environment:
      - APP_NAME=Framadate
      - DOMAIN=${DOMAIN:-framadate.localhost}
      - ADMIN_MAIL=${ADMIN_MAIL:-noreply@ethibox.fr}
      - MYSQL_USER=framadate
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
      - MYSQL_DB=framadate
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-myp@ssw0rd}
      - APACHE_RUN_USER=#1000
      - FRAMADATE_DEVMODE=${FRAMADATE_DEVMODE:-0}
      - SMTP_SERVER=${SMTP_SERVER:-localhost:25}
    volumes:
      - ${VOLUME_PATH}data:/var/www/framadate
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-framadate.localhost}
    networks:
      - internal
      - traefik

  mariadb:
    image: mariadb:10.3.14
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-myp@ssw0rd}
      - MYSQL_USER=framadate
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
      - MYSQL_DATABASE=framadate
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    networks:
      - internal

volumes:
  data:
  mariadb:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
