version: '3.7'

services:
  mailtrain:
    image: mailtrain/mailtrain:latest
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=mailtrain
      - MYSQL_USER=mailtrain
      - MYSQL_PASSWORD=myp@ssw0rd
      - URL_BASE_PUBLIC=${SCHEME:-http}://${DOMAIN:-mailtrain.localhost}
      - URL_BASE_SANDBOX=${SCHEME:-http}://${DOMAIN:-mailtrain.localhost}
      - URL_BASE_TRUSTED=${SCHEME:-http}://${DOMAIN:-mailtrain.localhost}
      - WWW_PROXY=true
    volumes:
      - ${VOLUME_PATH}data:/app/server/files
    deploy:
      labels:
        - traefik.port=3000
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-mailtrain.localhost}
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=mailtrain
      - MYSQL_USER=mailtrain
      - MYSQL_PASSWORD=myp@ssw0rd
    volumes:
      - ${VOLUME_PATH}mysql:/var/lib/mysql
    networks:
      - internal

  redis:
    image: redis:5.0.2-alpine
    networks:
      - internal

  mongo:
    image: mongo:4-xenial
    volumes:
      - ${VOLUME_PATH}mongo:/data/db
    networks:
      - internal

volumes:
  data:
  mysql:
  mongo:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
