# chown 2000:2000 data plugins config

version: "3.7"

services:
  app:
    image: mattermost/mattermost-prod-app:${VERSION:-5.21.0}
    volumes:
      - ${VOLUME_PATH}data:/mattermost/data
      - ${VOLUME_PATH}config:/mattermost/config
      - ${VOLUME_PATH}plugins:/mattermost/plugins
    environment:
      - MM_USERNAME=mattermost
      - MM_PASSWORD=myp@ssw0rd
      - MM_DBNAME=mattermost
      - MM_SERVICESETTINGS_SITEURL=${SCHEME:-http}://${DOMAIN:-mattermost.localhost}
      - MM_LOCALIZATIONSETTINGS_DEFAULTCLIENTLOCALE=${LOCALE:-fr}
      - MM_LOCALIZATIONSETTINGS_AVAILABLELOCALES=${LOCALE:-fr}
      - MM_EMAILSETTINGS_ENABLEPREVIEWMODEBANNER=FALSE
      - MM_EMAILSETTINGS_SMTPUSERNAME=${SMTP_USERNAME}
      - MM_EMAILSETTINGS_SMTPPASSWORD=${SMTP_PASSWORD}
      - MM_EMAILSETTINGS_SMTPSERVER=${SMTP_SERVER}
      - MM_EMAILSETTINGS_SMTPPORT=${SMTP_PORT}
    networks:
      - internal

  web:
    image: mattermost/mattermost-prod-web:${VERSION-5.21.0}
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-mattermost.localhost}
    networks:
      - internal
      - traefik

  db:
    image: postgres:9.6-alpine
    volumes:
      - ${VOLUME_PATH}db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mattermost
      - POSTGRES_PASSWORD=myp@ssw0rd
      - POSTGRES_DB=mattermost
    networks:
      - internal

volumes:
  data:
  config:
  plugins:
  db:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
