version: "3.7"

services:
  web:
    image: odoo:${VERSION:-13.0}
    volumes:
      - ${VOLUME_PATH}odoo:/var/lib/odoo
      - ${VOLUME_PATH}config:/etc/odoo
      - ${VOLUME_PATH}addons:/mnt/extra-addons
    environment:
      - USER=odoo
      - PASSWORD=myp@ssw0rd
    deploy:
      labels:
        - traefik.port=8069
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-odoo.localhost}
    networks:
      - internal
      - traefik

  db:
    image: postgres:10-alpine
    volumes:
      - ${VOLUME_PATH}db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myp@ssw0rd
      - POSTGRES_USER=odoo
    networks:
      - internal

volumes:
  odoo:
  config:
  addons:
  db:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
