version: "3.7"

services:
  peertube:
    image: chocobozzz/peertube:${VERSION:-v2.0.0-stretch}
    environment:
      - PEERTUBE_DB_USERNAME=postgres
      - PEERTUBE_DB_PASSWORD=myp@ssw0rd
      - PEERTUBE_WEBSERVER_HOSTNAME=${DOMAIN:-peertube.localhost}
      - PEERTUBE_WEBSERVER_PORT=${PORT:-80}
      - PEERTUBE_WEBSERVER_HTTPS=${HTTPS:-false}
      - PEERTUBE_ADMIN_EMAIL=${ADMIN_EMAIL:-admin@domain.tld}
      - PEERTUBE_SMTP_USERNAME=${SMTP_USERNAME}
      - PEERTUBE_SMTP_PASSWORD=${SMTP_PASSWORD}
      - PEERTUBE_SMTP_HOSTNAME=${SMTP_HOSTNAME}
      - PEERTUBE_SMTP_PORT=${SMTP_PORT:-25}
      - PEERTUBE_SMTP_FROM=${SMTP_FROM}
      - PEERTUBE_SMTP_TLS=${SMTP_TLS:-true}
      - PEERTUBE_SMTP_DISABLE_STARTTLS=false
      - PT_INITIAL_ROOT_PASSWORD=${PT_INITIAL_ROOT_PASSWORD:-myp@ssw0rd}
    volumes:
      - ${VOLUME_PATH}data:/data
      - ${VOLUME_PATH}config:/config
    deploy:
      labels:
        - traefik.port=9000
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-peertube.localhost}
    networks:
      - internal
      - traefik

  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myp@ssw0rd
      - POSTGRES_DB=peertube
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:4-alpine
    networks:
      - internal

volumes:
  data:
  config:
  postgres:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
