version: '3.7'

services:
  phpbb:
    image: bitnami/phpbb:${VERSION:-3.2.8}
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PHPBB_DATABASE_USER=root
      - PHPBB_DATABASE_NAME=phpbb
      - PHPBB_DATABASE_PASSWORD=myp@ssw0rd
      - PHPBB_USERNAME=${PHPBB_USERNAME:-admin}
      - PHPBB_PASSWORD=${PHPBB_PASSWORD:-myp@ssw0rd}
      - PHPBB_EMAIL=${EMAIL:-noreply@ethibox.fr}
    volumes:
      - ${VOLUME_PATH}phpbb:/bitnami
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-phpbb.localhost}
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.3.10
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=phpbb
      - MYSQL_USER=phpbb
      - MYSQL_PASSWORD=myp@ssw0rd
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    networks:
      - internal

volumes:
  phpbb:
  mariadb:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
