# mkdir -p data db && chmod 755 data db

version: '3'

services:
  db:
    image: mariadb:10.3.10
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-prestashop}
      MYSQL_USER: ${MYSQL_USER:-prestashop}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-myp@ssw0rd}
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

  prestashop:
    image: prestashop/prestashop:1.7.5.1
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/data:/var/www/html
    environment:
      DB_SERVER: db
      DB_USER: ${MYSQL_USER:-prestashop}
      DB_PASSWD: ${MYSQL_PASSWORD:-myp@ssw0rd}
      DB_NAME: ${MYSQL_DATABASE:-prestashop}
      PS_DOMAIN: ${DOMAIN:?err}
      PS_HANDLE_DYNAMIC_DOMAIN: ${PS_HANDLE_DYNAMIC_DOMAIN:-1}
      PS_LANGUAGE: ${PS_LANGUAGE:-fr}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      PS_ENABLE_SSL: ${PS_ENABLE_SSL:-1}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-destroy}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-secure}
      ADMIN_MAIL: ${ADMIN_MAIL:-demo@prestashop.com}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-prestashop_demo}
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - traefik
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
