# cp -r /tmp/YetiForceCRM/. /var/www/html
# Change /var/www/html/config/Main.php : public static $site_URL = 'https://site.fr/';

version: '3.7'

services:
  yetiforce:
    image: efero/yetiforcecrm:${VERSION:-5.2.0}
    environment:
      - DB_HOST_NAME=mariadb
      - DATABASE_NAME=yetiforce
      - DB_USER_NAME=yetiforce
      - DB_PASSWORD=myp@ssw0rd
      - DB_TYPE=mysql
      - DB_TCP_PORT=3306
      - DB_MANAGER=MysqlManager
    volumes:
      - ${VOLUME_PATH}data:/var/www/html
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-yetiforce.localhost}
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.3.14
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=yetiforce
      - MYSQL_USER=yetiforce
      - MYSQL_PASSWORD=myp@ssw0rd
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - internal

volumes:
  data:
  mariadb:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
