# DOMAIN=example.com docker stack deploy -c bookstack.yml bookstack

services:
  app:
    image: linuxserver/bookstack:${VERSION:-25.11.6}
    environment:
      - APP_URL=${SCHEME:-https}://${DOMAIN:-bookstack.localhost}
      - ALLOW_ROBOTS=${ALLOW_ROBOTS:-true}
      - APP_VIEWS_BOOKS=${APP_VIEWS_BOOKS:-grid}
      - APP_VIEWS_BOOKSHELF=${APP_VIEWS_BOOKS:-grid}
      - APP_VIEWS_BOOKSHELVES=${APP_VIEWS_BOOKS:-grid}
      - APP_KEY=${APP_KEY} # docker run -it --rm --entrypoint /bin/bash lscr.io/linuxserver/bookstack:latest appkey
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=myp@ssw0rd
      - MAIL_HOST=${SMTP_HOST}
      - MAIL_FROM=${SMTP_FROM}
      - MAIL_PORT=${SMTP_PORT:-587}
      - MAIL_USERNAME=${SMTP_USERNAME}
      - MAIL_PASSWORD=${SMTP_PASSWORD}
      - MAIL_DRIVER=${SMTP_DRIVER:-smtp}
      - MAIL_ENCRYPTION=${SMTP_ENCRYPTION:-tls}
      - MAIL_FROM_NAME=${SMTP_FROM_NAME:-BookStack}
    volumes:
      - ${VOLUME_PATH}data:/config
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
      labels:
        - traefik.enable=true
        - traefik.http.routers.bookstack-${NUMBER:-1}.rule=Host(`${DOMAIN:-bookstack.localhost}`)
        - traefik.http.routers.bookstack-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.bookstack-${NUMBER:-1}.service=bookstack-${NUMBER:-1}
        - traefik.http.routers.bookstack-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.bookstack-${NUMBER:-1}.loadbalancer.server.port=80
    networks:
      - internal
      - traefik

  mariadb:
    image: mariadb:10.5.9
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=myp@ssw0rd
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
    networks:
      - internal

volumes:
  mariadb:
  data:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
