# DOMAIN=example.com docker stack deploy -c calibre.yml calibre

services:
  calibre:
    image: crocodilestick/calibre-web-automated:${VERSION:-v4.0.6}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - HARDCOVER_TOKEN=${HARDCOVER_TOKEN}
      - NETWORK_SHARE_MODE=${NETWORK_SHARE_MODE:-false}
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
      labels:
        - traefik.enable=true
        - traefik.http.routers.calibre-${NUMBER:-1}.rule=Host(`${DOMAIN:-calibre.localhost}`)
        - traefik.http.routers.calibre-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.calibre-${NUMBER:-1}.service=calibre-${NUMBER:-1}
        - traefik.http.routers.calibre-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.calibre-${NUMBER:-1}.loadbalancer.server.port=8083
    volumes:
      - ${VOLUME_PATH}config:/config
      - ${VOLUME_PATH}books:/calibre-library
      - ${VOLUME_PATH}ingest:/cwa-book-ingest
    networks:
      - traefik

volumes:
  books:
  config:
  ingest:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
