# docker stack deploy -c crowdsec.yml crowdsec
# docker exec -it $(docker ps -qf name=crowdsec_crowdsec) cscli bouncers add traefik-bouncer

services:
  crowdsec:
    image: crowdsecurity/crowdsec:${VERSION:-v1.7.4}
    environment:
      - COLLECTIONS=${COLLECTIONS:-crowdsecurity/traefik}
      - CUSTOM_HOSTNAME=${CUSTOM_HOSTNAME:-crowdsec}
    volumes:
      - /var/log:/var/log:ro
      - ${VOLUME_PATH}config:/etc/crowdsec
      - ${VOLUME_PATH}data:/var/lib/crowdsec/data/
    networks:
      - traefik
      - internal

  bouncer:
    image: fbonalair/traefik-crowdsec-bouncer:latest
    environment:
      - CROWDSEC_BOUNCER_API_KEY=${CROWDSEC_BOUNCER_API_KEY}
      - CROWDSEC_AGENT_HOST=crowdsec:8080
    networks:
      - traefik
      - internal

volumes:
  data:
  config:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
