# DOMAIN=example.com docker stack deploy -c drawio.yml drawio

services:
  web:
    image: jgraph/drawio:${VERSION:-29.3.5}
    deploy:
      resources:
        limits:
          memory: 2G
      labels:
        - traefik.enable=true
        - traefik.http.routers.drawio-${NUMBER:-1}.rule=Host(`${DOMAIN:-drawio.localhost}`)
        - traefik.http.routers.drawio-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.drawio-${NUMBER:-1}.service=drawio-${NUMBER:-1}
        - traefik.http.routers.drawio-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.drawio-${NUMBER:-1}.loadbalancer.server.port=8080

networks:
  default:
    external: true
    name: traefik-net
