# DOMAIN=example.com docker stack deploy -c focalboard.yml focalboard
# chown -R 65534:65534 data

services:
  web:
    image: mattermost/focalboard:${VERSION:-7.11.4}
    volumes:
      - ${VOLUME_PATH}data:/opt/focalboard/data
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.focalboard-${NUMBER:-1}.rule=Host(`${DOMAIN:-focalboard.localhost}`)
        - traefik.http.routers.focalboard-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.focalboard-${NUMBER:-1}.service=focalboard-${NUMBER:-1}
        - traefik.http.routers.focalboard-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.focalboard-${NUMBER:-1}.loadbalancer.server.port=8000
    networks:
      - internal
      - traefik

volumes:
  data:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
