# DOMAIN=example.com docker stack deploy -c jenkins.yml jenkins

version: '3.8'

services:
  web:
    image: jenkinsci/blueocean:${VERSION:-1.24.8}
    user: root
    volumes:
      - ${VOLUME_PATH}data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.jenkins-${NUMBER:-1}.rule=Host(`${DOMAIN:-jenkins.localhost}`)
        - traefik.http.routers.jenkins-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.jenkins-${NUMBER:-1}.service=jenkins-${NUMBER:-1}
        - traefik.http.routers.jenkins-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.jenkins-${NUMBER:-1}.loadbalancer.server.port=8080

volumes:
  data:

networks:
  default:
    external: true
    name: traefik-net
