# DOMAIN=example.com docker stack deploy -c jitsi.yml jitsi

x-defaults: &defaults
  environment:
    - TZ=Europe/Paris
    - JVB_PORT=${JVB_PORT:-10000}
    - JVB_ADVERTISE_IPS=${JVB_ADVERTISE_IPS}
    - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
    - ENABLE_COLIBRI_WEBSOCKET_UNSAFE_REGEX=1
    - JIBRI_XMPP_PASSWORD=${JIBRI_XMPP_PASSWORD}
    - JIGASI_XMPP_PASSWORD=${JIGASI_XMPP_PASSWORD}
    - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
    - JIBRI_RECORDER_PASSWORD=${JIBRI_RECORDER_PASSWORD}
    - PUBLIC_URL=${SCHEME:-https}://${DOMAIN:-jitsi.localhost}
    - VIDEOBRIDGE_MAX_MEMORY=${VIDEOBRIDGE_MAX_MEMORY:-2048m}
    - ENABLE_HTTP_REDIRECT=0
    - ENABLE_LETS_ENCRYPT=0
    - DISABLE_HTTPS=1
    - ENABLE_AUTH=${ENABLE_AUTH:-0}
    - ENABLE_GUESTS=${ENABLE_GUESTS:-1}
    - AUTH_TYPE=${AUTH_TYPE:-internal}

services:
  web:
    <<: *defaults
    image: jitsi/web:${VERSION:-stable-10655}
    volumes:
      - ${VOLUME_PATH}web:/config
    deploy:
      resources:
        limits:
          memory: 2G
      labels:
        - traefik.enable=true
        - traefik.http.routers.jitsi-${NUMBER:-1}.rule=Host(`${DOMAIN:-jitsi.localhost}`)
        - traefik.http.routers.jitsi-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.jitsi-${NUMBER:-1}.service=jitsi-${NUMBER:-1}
        - traefik.http.routers.jitsi-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.routers.jitsi-${NUMBER:-1}.middlewares=jitsi-${NUMBER:-1}-block
        - traefik.http.middlewares.jitsi-${NUMBER:-1}-block.replacepathregex.regex=^/(.*)(${JITSI_BLOCK_REGEX:-nonexistentpath})(.*)$$
        - traefik.http.middlewares.jitsi-${NUMBER:-1}-block.replacepathregex.replacement=/static/offline.html
        - traefik.http.services.jitsi-${NUMBER:-1}.loadbalancer.server.port=80
    networks:
      - traefik
      - internal

  prosody:
    <<: *defaults
    image: jitsi/prosody:${VERSION:-stable-10655}
    volumes:
      - ${VOLUME_PATH}prosody:/config
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      internal:
        aliases:
          - ${XMPP_SERVER:-xmpp.meet.jitsi}

  jicofo:
    <<: *defaults
    image: jitsi/jicofo:${VERSION:-stable-10655}
    volumes:
      - ${VOLUME_PATH}jicofo:/config
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - internal

  jvb:
    <<: *defaults
    image: jitsi/jvb:${VERSION:-stable-10655}
    volumes:
      - ${VOLUME_PATH}jvb:/config
    ports:
      - target: ${JVB_PORT:-10000}
        published: ${JVB_PORT:-10000}
        protocol: udp
        mode: host
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - internal

volumes:
  web:
  jvb:
  jicofo:
  prosody:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
