# DOMAIN=example.com docker stack deploy -c mautic.yml mautic

version: '3.8'

services:
  nginx:
    image: ethibox/nginx-proxy
    command:
      - /bin/sh
      - -c
      - |
        sed -i -e 's/app:9000/'$$STACK_NAME'_app:9000/g' /etc/nginx/nginx.conf
        nginx -g 'daemon off;'
    environment:
      - STACK_NAME={{ index .Service.Labels "com.docker.stack.namespace" }}
    volumes:
      - ${VOLUME_PATH}data:/var/www/html:cached
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.mautic-${NUMBER:-1}.rule=Host(`${DOMAIN:-mautic.localhost}`)
        - traefik.http.routers.mautic-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.mautic-${NUMBER:-1}.service=mautic-${NUMBER:-1}
        - traefik.http.routers.mautic-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.mautic-${NUMBER:-1}.loadbalancer.server.port=80
    networks:
      - internal
      - traefik

  app:
    image: mautic/mautic:${VERSION:-v4-fpm}
    volumes:
      - ${VOLUME_PATH}data:/var/www/html:cached
    environment:
      - MAUTIC_DB_HOST=mariadb
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=myp@ssw0rd
      - PHP_MEMORY_LIMIT=2048M
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.5.9
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=mautic
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=myp@ssw0rd
    networks:
      - internal

volumes:
  mariadb:
  data:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
