# DOMAIN=example.com docker stack deploy -c memos.yml memos

services:
  web:
    image: neosmemo/memos:${VERSION:-0.25.0}
    volumes:
      - ${VOLUME_PATH}memos:/var/opt/memos
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.memos-${NUMBER:-1}.rule=Host(`${DOMAIN:-memos.localhost}`)
        - traefik.http.routers.memos-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.memos-${NUMBER:-1}.service=memos-${NUMBER:-1}
        - traefik.http.routers.memos-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.memos-${NUMBER:-1}.loadbalancer.server.port=5230

volumes:
  memos:

networks:
  default:
    external: true
    name: traefik-net
