# DOMAIN=example.com DOMAIN_CONSOLE=console.example.com docker stack deploy -c minio.yml minio

version: '3.8'

services:
  web:
    image: minio/minio:${VERSION:-RELEASE.2024-05-10T01-41-38Z}
    command: server /data --console-address ":9001"
    volumes:
      - ${VOLUME_PATH}data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-myp@ssw0rd}
      - MINIO_BROWSER_REDIRECT_URL=${SCHEME:-https}://${DOMAIN_CONSOLE:?}
      - MINIO_SERVER_URL=${SCHEME:-https}://${DOMAIN:-minio.localhost}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.minio-${NUMBER:-1}.rule=Host(`${DOMAIN:-minio.localhost}`)
        - traefik.http.routers.minio-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.minio-${NUMBER:-1}.service=minio-${NUMBER:-1}
        - traefik.http.routers.minio-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.minio-${NUMBER:-1}.loadbalancer.server.port=9000
        - traefik.http.routers.minio-console-${NUMBER:-1}.rule=Host(`${DOMAIN_CONSOLE:?}`)
        - traefik.http.routers.minio-console-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.minio-console-${NUMBER:-1}.service=minio-console-${NUMBER:-1}
        - traefik.http.routers.minio-console-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.minio-console-${NUMBER:-1}.loadbalancer.server.port=9001

volumes:
  data:

networks:
  default:
    external: true
    name: traefik-net
