# DOMAIN=example.com docker stack deploy -c monitoring.yml monitoring
# chown -R nobody:root prometheus/

services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.3.1}
    user: root
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_FROM_ADDRESS=${SMTP_FROM:-noreply@example.com}
      - GF_SMTP_HOST=${SMTP_HOST:-smtp.example.com:587}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD:-myp@ssw0rd}
      - GF_SMTP_USER=${SMTP_USERNAME:-noreply@example.com}
      - GF_SERVER_ROOT_URL=${SCHEME:-https}://${DOMAIN:-grafana.localhost}
    volumes:
      - ${VOLUME_PATH}grafana:/var/lib/grafana
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.grafana-${NUMBER:-1}.rule=Host(`${DOMAIN:-grafana.localhost}`)
        - traefik.http.routers.grafana-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.grafana-${NUMBER:-1}.service=grafana-${NUMBER:-1}
        - traefik.http.routers.grafana-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.grafana-${NUMBER:-1}.loadbalancer.server.port=3000
    networks:
      - internal
      - traefik

  prometheus:
    image: prom/prometheus:v3.8.1
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ ! -f /etc/prometheus/prometheus.yml ]; then
        cat << EOF > /etc/prometheus/prometheus.yml
        global:
          scrape_interval:     30s
          evaluation_interval: 30s

        scrape_configs:
          - job_name: prometheus
            metrics_path: /prometheus/metrics
            static_configs:
              - targets: ['localhost:9090']

          - job_name: node-exporter
            dns_sd_configs:
            - names:
              - tasks.node-exporter
              type: A
              port: 9100

          - job_name: cadvisor
            dns_sd_configs:
            - names:
              - tasks.cadvisor
              type: A
              port: 8080

          - job_name: process-exporter
            dns_sd_configs:
            - names:
              - tasks.process-exporter
              type: A
              port: 9256
        EOF
        fi

        if [ ! -f /etc/prometheus/process-conf.yml ]; then
        cat << EOF > /etc/prometheus/process-conf.yml
        process_names:
          - name: "{{.Comm}}"
            cmdline:
            - '.+'
        EOF
        fi

        prometheus --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/prometheus \
        --storage.tsdb.retention.time=7d \
        --storage.tsdb.retention.size=20GB \
        --storage.tsdb.wal-compression \
        --web.console.libraries=/usr/share/prometheus/console_libraries \
        --web.console.templates=/usr/share/prometheus/consoles \
        --web.route-prefix=/prometheus \
        --web.external-url=${SCHEME:-https}://${DOMAIN:-grafana.localhost}/prometheus
    volumes:
      - ${VOLUME_PATH}prometheus:/prometheus
      - ${VOLUME_PATH}config:/etc/prometheus/
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.grafana-prom-${NUMBER:-1}.rule=Host(`${DOMAIN:-grafana.localhost}`) && PathPrefix(`/prometheus/`)
        - traefik.http.routers.grafana-prom-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.grafana-prom-${NUMBER:-1}.service=grafana-prom-${NUMBER:-1}
        - traefik.http.routers.grafana-prom-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.grafana-prom-${NUMBER:-1}.loadbalancer.server.port=9090
        - traefik.http.routers.grafana-prom-${NUMBER:-1}.middlewares=grafana-prom-${NUMBER:-1}-auth
        - traefik.http.middlewares.grafana-prom-${NUMBER:-1}-auth.basicauth.users=${PROM_USER:-admin}:${PROM_PASSWORD:-htpasswd} # htpasswd -bnBC 10 'admin' 'myp@ssw0rd'
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    networks:
      - internal
      - traefik

  cadvisor:
    image: ghcr.io/google/cadvisor:0.55.1
    command: -docker_only=true -housekeeping_interval=15s -disable_metrics=disk,diskIO,tcp,udp,percpu,sched,process,advtcp,hugetlb,referenced_memory
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
    networks:
      - internal

  node-exporter:
    image: prom/node-exporter:v1.10.2
    hostname: "{{.Node.Hostname}}"
    volumes:
      - /:/rootfs:ro
      - /mnt:/mnt:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc/hostname:/etc/hostname:ro
    environment:
      - NODE_ID={{.Node.ID}}
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - internal

  process-exporter:
    image: ncabatoff/process-exporter:0.8.7
    command: --procfs /host/proc -config.path /etc/process-exporter/process-conf.yml
    volumes:
      - /proc:/host/proc:ro
      - ${VOLUME_PATH}config:/etc/process-exporter:ro
    networks:
      - internal

volumes:
  config:
  grafana:
  prometheus:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
