# DOMAIN=example.com docker stack deploy -c odoo.yml odoo

x-odoo: &odoo
  image: odoo:${VERSION:-18.0}
  volumes:
    - ${VOLUME_PATH}config:/etc/odoo
    - ${VOLUME_PATH}odoo:/var/lib/odoo
    - ${VOLUME_PATH}addons:/mnt/extra-addons

services:
  init:
    <<: *odoo
    user: root
    command:
      - /bin/sh
      - -c
      - |
        if [ ! -f /etc/odoo/odoo.conf ]; then
        cat << EOF > /etc/odoo/odoo.conf
        [options]
        addons_path = /mnt/extra-addons
        data_dir = /var/lib/odoo
        EOF
        fi
        chown -R odoo:odoo /etc/odoo /var/lib/odoo
    deploy:
      restart_policy:
        condition: on-failure

  web:
    <<: *odoo
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=myp@ssw0rd
      - DB_PORT_5432_TCP_ADDR=postgres
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
      labels:
        - traefik.enable=true
        - traefik.http.routers.odoo-${NUMBER:-1}.rule=Host(`${DOMAIN:-odoo.localhost}`)
        - traefik.http.routers.odoo-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.odoo-${NUMBER:-1}.service=odoo-${NUMBER:-1}
        - traefik.http.routers.odoo-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.routers.odoo-${NUMBER:-1}.middlewares=odoo-${NUMBER:-1}
        - traefik.http.services.odoo-${NUMBER:-1}.loadbalancer.server.port=8069
        - traefik.http.middlewares.odoo-${NUMBER:-1}.headers.customRequestHeaders.X-Forwarded-Proto=${SCHEME:-https}
    networks:
      - internal
      - traefik

  postgres:
    image: postgres:${POSTGRES_VERSION:-16-alpine}
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myp@ssw0rd
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "odoo"]
    volumes:
      - ${VOLUME_PATH}db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
    networks:
      - internal

volumes:
  db:
  odoo:
  config:
  addons:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
