# DOMAIN=example.com docker stack deploy -c rainloop.yml rainloop

version: '3.8'

services:
  rainloop:
    image: hardware/rainloop:${VERSION:-latest}
    volumes:
      - ${VOLUME_PATH}rainloop:/rainloop/data
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.rainloop-${NUMBER:-1}.rule=Host(`${DOMAIN:-rainloop.localhost}`)
        - traefik.http.routers.rainloop-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.rainloop-${NUMBER:-1}.service=rainloop-${NUMBER:-1}
        - traefik.http.routers.rainloop-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.rainloop-${NUMBER:-1}.loadbalancer.server.port=8888

networks:
  default:
    external: true
    name: traefik-net
