# DOMAIN=example.com docker stack deploy -c scrumblr.yml scrumblr

services:
  scrumblr:
    image: ${IMAGE:-ethibox/scrumblr}:${VERSION:-latest}
    deploy:
      resources:
        limits:
          memory: 2G
      labels:
        - traefik.enable=true
        - traefik.http.routers.scrumblr-${NUMBER:-1}.rule=Host(`${DOMAIN:-scrumblr.localhost}`)
        - traefik.http.routers.scrumblr-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.scrumblr-${NUMBER:-1}.service=scrumblr-${NUMBER:-1}
        - traefik.http.routers.scrumblr-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.scrumblr-${NUMBER:-1}.loadbalancer.server.port=1000
    networks:
      - internal
      - traefik

  redis-dock:
    image: redis:6-alpine
    volumes:
      - ${VOLUME_PATH}redis:/data
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - internal

volumes:
  redis:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
