# DOMAIN=example.com docker stack deploy -c searx.yml searx

version: '3.8'

services:
  web:
    image: searx/searx:${VERSION:-latest}
    environment:
      - BASE_URL=${SCHEME:-https}://${DOMAIN:-searx.localhost}
      - BIND_ADDRESS=0.0.0.0:8080
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.searx-${NUMBER:-1}.rule=Host(`${DOMAIN:-searx.localhost}`)
        - traefik.http.routers.searx-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.searx-${NUMBER:-1}.service=searx-${NUMBER:-1}
        - traefik.http.routers.searx-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.searx-${NUMBER:-1}.loadbalancer.server.port=8080

networks:
  default:
    external: true
    name: traefik-net
