# DOMAIN=example.com docker stack deploy -c taiga.yml taiga
# docker exec -it $(docker ps -qf name=taiga_back) python manage.py createsuperuser

x-defaults: &defaults
  environment:
    - SECRET_KEY=${SECRET_KEY:-mys3cr3t}
    - TAIGA_SITES_SCHEME=${SCHEME:-https}
    - TAIGA_ASYNC_RABBITMQ_HOST=rabbitmq
    - TAIGA_EVENTS_RABBITMQ_HOST=rabbitmq
    - TAIGA_SECRET_KEY=${SECRET_KEY:-mys3cr3t}
    - TAIGA_SITES_DOMAIN=${DOMAIN:-taiga.localhost}
    - POSTGRES_DB=taiga
    - POSTGRES_USER=taiga
    - POSTGRES_HOST=postgres
    - POSTGRES_PASSWORD=myp@ssw0rd
    - RABBITMQ_USER=taiga
    - RABBITMQ_VHOST=taiga
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_PASS=mypassword
  volumes:
    - ${VOLUME_PATH}static:/taiga/static
    - ${VOLUME_PATH}media:/taiga/media

services:
  web:
    image: ethibox/nginx-proxy:test3
    environment:
      - NGINX_TEMPLATE=${NGINX_TEMPLATE:-/etc/nginx/taiga.template}
      - SERVER_NAME={{ index .Service.Labels "com.docker.stack.namespace" }}
    volumes:
      - ${VOLUME_PATH}static:/taiga/static
      - ${VOLUME_PATH}media:/taiga/media
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.taiga-${NUMBER:-1}.rule=Host(`${DOMAIN:-taiga.localhost}`)
        - traefik.http.routers.taiga-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.taiga-${NUMBER:-1}.service=taiga-${NUMBER:-1}
        - traefik.http.routers.taiga-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.taiga-${NUMBER:-1}.loadbalancer.server.port=80
    networks:
      - internal
      - traefik

  front:
    <<: *defaults
    image: taigaio/taiga-front:${VERSION:-6.9.0}
    networks:
      - internal

  back:
    <<: *defaults
    image: taigaio/taiga-back:${VERSION:-6.9.0}
    volumes:
      - ${VOLUME_PATH}static:/taiga-back/static
      - ${VOLUME_PATH}media:/taiga-back/media
    networks:
      - internal

  async:
    <<: *defaults
    image: taigaio/taiga-back:${VERSION:-6.9.0}
    entrypoint: /taiga-back/docker/async_entrypoint.sh
    networks:
      - internal

  events:
    <<: *defaults
    image: taigaio/taiga-events:${VERSION:-6.9.0}
    networks:
      - internal

  protected:
    <<: *defaults
    image: taigaio/taiga-protected:${VERSION:-6.9.0}
    networks:
      - internal

  rabbitmq:
    <<: *defaults
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_ERLANG_COOKIE=${SECRET_KEY:-mys3cr3t}
      - RABBITMQ_DEFAULT_PASS=mypassword
      - RABBITMQ_DEFAULT_VHOST=taiga
      - RABBITMQ_DEFAULT_USER=taiga
    volumes:
      - ${VOLUME_PATH}rabbitmq:/var/lib/rabbitmq
    networks:
      - internal

  postgres:
    image: postgres:${POSTGRES_VERSION:-16-alpine}
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=myp@ssw0rd
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "taiga"]
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  media:
  static:
  rabbitmq:
  postgres:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
