# DOMAIN=example.com docker stack deploy -c twenty.yml twenty

x-defaults: &defaults
  image: twentycrm/twenty:${VERSION:-v1.16.7}
  environment:
    - PORT=3000
    - PG_DATABASE_URL=postgres://twenty:mypassw0rd@{{ index .Service.Labels "com.docker.stack.namespace" }}_postgres:5432/${POSTGRES_DB:-twenty}
    - SERVER_URL=${SCHEME:-https}://${DOMAIN:-twenty.localhost}
    - FRONT_BASE_URL=${SCHEME:-https}://${DOMAIN:-twenty.localhost}
    - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    - SIGN_IN_PREFILLED=${SIGN_IN_PREFILLED:-false}
    - STORAGE_TYPE=${STORAGE_TYPE:-local}
    - ENABLE_DB_MIGRATIONS=${ENABLE_DB_MIGRATIONS:-true}
    - APP_SECRET=${APP_SECRET:-onoUicllnXTKiO6J+OGSFQFtdw9uyucAyxw3ztKXu+8=} # openssl rand -base64 32
  volumes:
    - ${VOLUME_PATH}data:/app/packages/twenty-server/.local-storage
    - ${VOLUME_PATH}docker:/app/docker-data

services:
  init:
    image: busybox
    command: chown -R 1000:1000 /app/packages/twenty-server/.local-storage /app/docker-data
    user: root
    volumes:
      - ${VOLUME_PATH}data:/app/packages/twenty-server/.local-storage
      - ${VOLUME_PATH}docker:/app/docker-data
    deploy:
      restart_policy:
        condition: on-failure

  app:
    <<: *defaults
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
      labels:
        - traefik.enable=true
        - traefik.http.routers.twenty-${NUMBER:-1}.rule=Host(`${DOMAIN:-twenty.localhost}`)
        - traefik.http.routers.twenty-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.twenty-${NUMBER:-1}.service=twenty-${NUMBER:-1}
        - traefik.http.routers.twenty-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.twenty-${NUMBER:-1}.loadbalancer.server.port=3000
    networks:
      - traefik
      - internal

  worker:
    <<: *defaults
    command: ["yarn", "worker:prod"]
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
    networks:
      - internal

  redis:
    image: redis:6-alpine
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
    networks:
      - internal

  postgres:
    image: postgres:${POSTGRES_VERSION:-16-alpine}
    environment:
      - POSTGRES_DB=twenty
      - POSTGRES_USER=twenty
      - POSTGRES_PASSWORD=mypassw0rd
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "twenty"]
    volumes:
      - ${VOLUME_PATH}postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2G}
    networks:
      - internal

volumes:
  data:
  docker:
  postgres:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
