# DOMAIN=example.com docker stack deploy -c waiting.yml waiting

services:
  waiting:
    image: nginx:${VERSION:-alpine}
    entrypoint: /bin/sh
    command:
      - -c
      - |
        wget -O /usr/share/nginx/html/index.html https://gist.githubusercontent.com/johackim/e7a4ca2f00b587c890849586ac89d3a1/raw/waiting.html
        nginx -g 'daemon off;'
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.waiting-${NUMBER:-1}.rule=Host(`${DOMAIN:-waiting.localhost}`)
        - traefik.http.routers.waiting-${NUMBER:-1}.priority=50
        - traefik.http.routers.waiting-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.waiting-${NUMBER:-1}.service=waiting-${NUMBER:-1}
        - traefik.http.routers.waiting-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.waiting-${NUMBER:-1}.loadbalancer.server.port=80
        - traefik.http.routers.waiting-${NUMBER:-1}.middlewares=waiting-${NUMBER:-1}
        - traefik.http.middlewares.waiting-${NUMBER:-1}.redirectregex.regex=^https?:\/\/(.+?)\/(.+)$$
        - traefik.http.middlewares.waiting-${NUMBER:-1}.redirectregex.replacement=https://$${1}/
        - traefik.http.middlewares.waiting-${NUMBER:-1}.redirectregex.permanent=false

networks:
  default:
    external: true
    name: traefik-net
