# DOMAIN=example.com docker stack deploy -c wekan.yml wekan

services:
  wekan:
    image: wekanteam/wekan:${VERSION:-v8.18}
    environment:
      - MONGO_URL=mongodb://mongo:27017/wekan
      - VIRTUAL_HOST=${DOMAIN:-wekan.localhost}
      - ROOT_URL=${SCHEME:-https}://${DOMAIN:-wekan.localhost}
      - MAIL_URL=smtp://${SMTP_USERNAME}:${SMTP_PASSWORD}@${SMTP_HOST}:${SMTP_PORT:-587}
      - MAIL_FROM=${SMTP_FROM:-noreply@example.com}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.wekan-${NUMBER:-1}.rule=Host(`${DOMAIN:-wekan.localhost}`)
        - traefik.http.routers.wekan-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.wekan-${NUMBER:-1}.service=wekan-${NUMBER:-1}
        - traefik.http.routers.wekan-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.wekan-${NUMBER:-1}.loadbalancer.server.port=8080
    networks:
      - traefik
      - internal

  mongo:
    image: mongo:8.2
    volumes:
      - ${VOLUME_PATH}mongo:/data/db
    networks:
      - internal

volumes:
  mongo:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
